# Generated by Django 3.2.5 on 2021-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
