# Generated by Django 3.2.5 on 2021-07-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='messages',
            field=models.CharField(blank=True, max_length=10001),
        ),
    ]
