# Generated by Django 3.2.5 on 2021-07-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.CharField(blank=True, max_length=32, primary_key=True, serialize=False),
        ),
    ]
